var folder = companyhome.childByNamePath('/Sites/sequencing/documentLibrary/Collaborations');
var collab = folder.createNode("1000-AG-GH-HEMMINGWAY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1001-PF-ML-DJIMDE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1002-AG-BFUG-LAWNICZAK", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1003-AG-KEGM-BURT", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1004-PF-BF-OUEDRAOGO", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1005-PF-GM-JALLOW", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1006-PF-GM-CONWAY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1007-PF-TZ-DUFFY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1008-PF-SEA-RINGWALD", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1009-PF-KH-PLOWE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1010-PF-TH-ANDERSON", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1011-PF-KH-SU", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1012-PF-KH-WHITE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1013-PF-PEGB-BRANCH", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1014-PF-SSA-SUTHERLAND", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1015-PF-KE-NZILA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1016-PF-TH-NOSTEN", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1017-PF-GH-AMENGA-ETEGO", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1018-PF-GB-NEWBOLD", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1019-AG-CM-COHUET", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1020-PF-VN-BONI", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1021-PF-PG-MUELLER", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1022-PF-MW-OCHOLLA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1023-PF-CO-ECHEVERRI-GARCIA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1024-PF-UG-BOUSEMA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1025-PF-KH-PLOWE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1026-PF-GN-CONWAY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1027-PF-KE-BULL", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1028-AG-WAGB-VERNICK", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1029-AG-GB-LEVASHINA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1030-AG-GB-DONNELLY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1031-PF-SEA-PLOWE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1032-PF-BRHN-NEWBOLD", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1033-PF-BRGHSEA-SU", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1034-PF-BRSEA-RAYNER", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1035-PF-PNGB-CAMPINO", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1036-PF-VN-NZILA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1037-PFD-GM-CONWAY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1038-PF-SD-HVIID", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1039-PF-PFLAB9-BAKER", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1040-PF-GB-HAMILTON", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1041-PF-US-FERDIG", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1042-PF-HN-RANFORD-CARTWRIGHT", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1043-PF-GB-RAYNER", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1044-PF-KH-FAIRHURST", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1045-PF-PN-MUELLER", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1046-PV-BR-FERRERIA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1047-PV-LK-KARUNAWEERA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1048-PV-SVSEA-PRICE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1049-PV-VN-BONI", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1050-PV-PN-MUELLER", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1051-PV-KH-HOSTETLER", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1052-PF-TRAC-WHITE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1053", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1054", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1055-AG-SSA-DONNELLY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1056-AG-WAEA-SHARAKHOV", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1057", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1058", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1059", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1060-PF-ML-DIAKITE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1061-PF-GM-DALESSANDRO", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1062-PF-PG-BARRY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1063", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1064", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1065", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1066-PF-KE-MACKINNON", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1067-PF-ML-FAIRHURST", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1068", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1069", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1070", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1071", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1072", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1073", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1074", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1075", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1076", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1077", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1078", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1079", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1080", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1081", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1082", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1083-PF-GH-CONWAY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1084", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1085-PV-KH-FAIRHURST", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1086-PB-GB-IANTORNO", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1087-AN-HAPMAP-DONNELLY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1088-PF-SZTZ-GREENHOUSE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1089-R&D-GB-ALCOCK", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1090-AG-MULTI-VERNICK", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1091-PF-NG-AMODU", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1092", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1093-PF-CM-APINJOH", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1094-PF-GH-AMENGA-ETEGO", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1095-PF-TZ-ISHENGOMA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1096-PF-GH-GHANSAH", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1097-PF-ML-MAIGA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1098-PF-ET-GOLASSA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1099-PF-CD-TSHEFU", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1100-PF-CI-YAVO", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1101-PF-CD-ONYAMBOKO", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1102-PF-MG-RANDRIANARIVELOJOSIA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1103-PF-PDN-GMSN-NGWA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1104-PF-LAB-WENDLER", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1105-AG-WA-DJOGBENOU", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1106-PV-MULTI-PRICE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1107-PF-KEN-KAMAU", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1108-PF-GAB-BOUYOU-AKOTET", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1109-AG-COLONIES-DONNELLY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1110-AG-GM-GODFRAY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1111-PF-LAB3D7-BULL", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1112-AG-LABCROSS-WEILL", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1113-PF-PDN-DBS-GM-AMAMBUA-NGWA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1114-PF-PDN-DBS-GH-GHANSAH", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1115-PF-PDN-DBS-TZ-ISHENGOMA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1116-PF-PDN-DBS-CD-MUMBA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1117-PF-PDN-DBS-KEN-KAMAU", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1118-PF-PDN-DBS-ET-GOLASSA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1119-PF-PDN-DBS-GH-AMENGA-ETEGO", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1120-PF-PDN-DBS-GAB-BOUYOU-AKOTET", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1121-PF-PDN-DBS-MG-RANDRIANARIVELOJOSIA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1122-PF-PDN-DBS-ML-MAIGA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1123-PF-PDN-DBS-CM-APINJOH", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1124-PF-PDN-DBS-CI-YAVO", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1125-PF-TH-NOSTEN", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1126-PF-LAB-FAIRHURST", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1127-PF-ML-SOULEYMANE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1128-PV-GSKMULTI-RAYNER", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1129-AG-MULTI-VERNICK", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1130-AG-GM-CAPUTO", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1131-PF-BJ-BERTIN", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1132-PF-K1000g-DBS-KE-BEJON", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1133-PF-LAB-MERRICK", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1134-PF-ML-CONWAY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1135-PF-SN-CONWAY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1136-PF-GM-NGWA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1137-PF-GM-DALESSANDRO", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1138-PF-CD-FANELLO", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1139-HUM-CD-FANELLO", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1140-PF-ML-DUFFY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1141-PF-GM-CLAESSENS", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1142-HUM-GM-WGS-GGVP", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1143-HUM-GM-CP3-WGS", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1144-HUM-GM-CP1-GMSM", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1145-PF-PE-GAMBOA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1146-PF-MULTI-PRICE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1147-PF-MR-CONWAY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1148-PF-BD-MAUDE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1149-PF-MM-RINGWALD", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1150-PF-Pf3KLAB-CONWAY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1151-PF-GH-AMENGA-ETEGO", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1152-PF-DBS-GH-AMENGA-ETEGO", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1153-PF-Pf3KLAB-KWIATKOWSKI", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1154-PF-TH-PRICE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1155-PF-ID-PRICE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1156-PV-ID-PRICE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1157-PV-MULTI-PRICE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1158-PV-PG-BARRY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1159-PK-MY-RAYNER", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1160-PF-MULTI-HAMILTON", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1161-PV-ID-PRICE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1162-PF-GM-NGWA-SM", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1163-PF-GH-GHANSAH-SM", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1164-PF-ML-DJIMDE-SM", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1165-PF-CM-APINJOH-SM", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1166-PF-KE-BEJON-SM", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1167-PF-TZ-ISHENGOMA-SM", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1168-PF-GH-AMENGA-ETEGO-SM", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1169-PF-CO-CORREDOR", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1170-PV-CO-CORREDOR", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1171-DEV-SPOT", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1172-PF-KH-FAIRHURST-SM", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1173-AN-KE-MIDEGA", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1174-HUM-KE-CP1", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1175-VO-KH-STLAURENT", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1176-PF-KE-CP1", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1177-VO-ML-LEHMANN", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1178-VO-UG-LAWNICZAK", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1179-PF-KH-TME-VONSEIDLEIN", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1180-PF-TRAC2-DONDORP", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1181-PF-VN-THUY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1182-PF-GM-DALESSANDRO-SM", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1183-PF-GH-AWANDARE-SM", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1184-PF-ET-GOLASSA-SM", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1185-PF-KH-KYLE", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1186-PF-CD-FANELLO", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
var collab = folder.createNode("1187-VO-CM-BESANSKY", "cggh:collaborationFolder");
collab.addAspect("{http://alfresco.cggh.org/model/custom/1.0}collaborationData");
collab.save();
